---

- name: install named
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - bind
    - bind-utils

- name: restore selinux context for named
  command: restorecon -R /var/named

- name: create domain zone file
  template:
    src: zone.db.j2
    dest: /var/named/zones/{{domain}}.db
    owner: named
    group: named
  name: restart named

- name: configure named.conf
  template:
    src: named.conf.j2
    dest: /etc/named/named.conf
    owner: named
    group: named
  notify: restart named

- name: restore selinux context for named
  command: restorecon -R /etc/named.conf

- name: Add DNS rules to firewalld
  firewalld:
    service: dns
    permanent: True
    immediate: True
    state: enabled
