---

- name: Create IPA cert dir
  when: inventory_hostname in groups['masters']
  file:
    name: /etc/origin/master/
    state: directory
    mode: 0755
    owner: root
    group: root

- name: get IPA CA certificate
  when: inventory_hostname in groups['masters'] and use_idm
  get_url:
    url: http://idm.example.com/ipa/config/ca.crt
    dest: /etc/origin/master/ipa-ca.crt
    mode: 0440
    owner: root
    group: root

- name: install httpd-passwd
  when: inventory_hostname in groups['masters'] and not use_idm
  yum:
    name: httpd-tools
    state: present

- name: create file to openshift-password
  when: inventory_hostname in groups['masters'] and not use_idm
  file:
     name: /etc/origin/master/openshift-passwd
     state: touch
     mode: 0640
     owner: root
     group: root

- name: create users
  when: inventory_hostname in groups['masters'] and not use_idm
  command: htpasswd -b  /etc/origin/master/openshift-passwd {{ item }} 'r3dh4t1!'
  with_items:
    - andrew
    - karla
    - marina
