---
# handlers file for basics

- name: restart named
  service:
    name: named
    enabled: true
    state: restarted

- name: restore named context
  command: restorecon -R {{ item }}
  with_items:
    - /var/named
    - /etc/named.conf

- name: restart nfs services
  service:
    name: '{{  item }}'
    enabled: true
    state: restarted
  with_items:
    - rpcbind
    - nfs-server
    - nfs-lock
    - nfs-idmap
