---

- name: Add new hosts ha masters
  when: install_ha
  add_host: name={{ item }} groups=masters
  with_items:
    - master1.example.com
    - master2.example.com
    - master3.example.com

- name: Add new hosts ha etcd
  when: install_ha
  add_host: name={{ item }} groups=etcd
  with_items:
    - master1.example.com
    - master2.example.com
    - master3.example.com

- name: Add new hosts ha masters
  when: install_ha
  add_host: name={{ item }} groups=nodes
  with_items:
    - master1.example.com
    - master2.example.com
    - master3.example.com
    - infranode1.example.com
    - infranode2.example.com
    - node1.example.com
    - node2.example.com
    - node3.example.com
    - node4.example.com
    - node5.example.com
    - node6.example.com

- name: Add new hosts ha infranodes
  when: install_ha
  add_host: name={{ item }} groups=infranodes
  with_items:
    - infranode1.example.com
    - infranode2.example.com

- name: Add new host lb
  when: install_ha and install_lb
  add_host: name={{ item }} groups=lb
  with_items:
    - loadbalance1.example.com

- name: Add new host master
  when: not install_ha
  add_host: name={{ item }} groups=masters
  with_items:
    - master1.example.com

- name: Add new host etcd
  when: not install_ha
  add_host: name={{ item }} groups=etcd
  with_items:
    - master1.example.com

- name: Add new node hosts
  when: not install_ha
  add_host: name={{ item }} groups=nodes
  with_items:
    - master1.example.com
    - infranode1.example.com
    - node1.example.com
    - node2.example.com
    - node3.example.com

- name: Add new hosts ha infranodes
  when: not install_ha
  add_host: name={{ item }} groups=infranodes
  with_items:
    - infranode1.example.com
