---
# defaults file for basics

domain: cloudapps-{{guid}}.oslab.opentlc.com

exports:
  - registry
  - vol1
  - vol2
  - vol3
  - es-storage
  - jenkins
  - cassandra
  - nexus

users:
  - admin1
  - admin2
  - andrew
  - david
  - karla
  - marina
  - payment1
  - payment2
  - portal1
  - portal2
  - prod1
  - prod2
